# Generated by Django 3.0 on 2021-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('bname', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('extc', 'EXTC'), ('chemical', 'CHEMICAL'), ('mechanical', 'MECHANICAL')], default='cse', max_length=15)),
                ('year', models.CharField(choices=[('first', 'FE'), ('second', 'SE'), ('third', 'TE'), ('fourth', 'BE')], default='first', max_length=10)),
            ],
        ),
    ]
