# Generated by Django 3.0 on 2021-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('bname', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('Chemical', 'CHEMICAL'), ('Mechanical', 'MECHANICAL')], default='cse', max_length=15)),
                ('year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='first', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=50)),
                ('b_id', models.IntegerField()),
                ('b_name', models.CharField(max_length=50)),
                ('dateofissue', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid2', models.IntegerField()),
                ('bid2', models.IntegerField()),
                ('dateofreturn', models.DateField()),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
    ]
