# Generated by Django 3.0 on 2021-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('bid', models.IntegerField()),
                ('bname', models.CharField(max_length=50)),
                ('dateofissue', models.DateField()),
            ],
        ),
    ]
