# Generated by Django 3.0 on 2021-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210411_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid2', models.IntegerField()),
                ('bid2', models.IntegerField()),
                ('dateofreturn', models.DateField()),
            ],
        ),
    ]
