# Generated by Django 3.0 on 2021-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_returnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
