# Generated by Django 3.0 on 2021-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_returnbook_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('Chemical', 'CHEMICAL'), ('Mechanical', 'MECHANICAL')], default='cse', max_length=15),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='first', max_length=10),
        ),
    ]
